version: '3.7'
services:
  db:
    image: mysql:8.0.20
    platform: linux/x86_64
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=NO_ENGINE_SUBSTITUTION
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"

  web:
    build: .
    command:
      sh -c "rm -f /kanban-ban/tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/kanban-ban:cached
      - bundle:/usr/local/bundle:cached
      - /kanban-ban/vendor
      - /kanban-ban/tmp
      - /kanban-ban/log
      - /kanban-ban/.git

volumes:
  db_data:
  bundle:
