default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "password"
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: kanban_ban_development

test:
  <<: *default
  database: kanban_ban_development_test

production:
  <<: *default
  database: kanban_ban_development_pro
